name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Ejecutar tests con pytest y generar cobertura
        run: |
          python -m pytest tests/unit/ --cov=src --cov-report=term --cov-report=xml
      - name: Guardar reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Guardar binario compilado
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-dist
          path: dist/
